### ISSUE TITLE
Disable "Keep Toshocat minimized..." if "Run Toshocat on Startup" is unchecked

### ISSUE THREAD

**Issue by JasonEtco** [tofuness/Toshocat#11]
In the Settings tab:

Rather than saying 'Keep Toshocat minimized _if run on startup_' it would be a better idea to just disable the checkbox by adding the `disabled` attribute to it when the 'Run Toshocat on Windows Startup' is unchecked.

Should be an easy fix; I can make a PR if you'd like.

**Comment by tofuness** [comment]
Feel free to submit a PR, @JasonEtco ! Let me know if you need any help :smile:

**Comment by JasonEtco** [comment]
Closing this because the repo isn't active anymore 😄
