### ISSUE TITLE
Hummingbird sync botched

### ISSUE THREAD

**Issue by matthewdias** [tofuness/Toshocat#6]
All my ratings get rounded to even numbers, and many shows are in the wrong lists.

**Comment by tofuness** [comment]
Known problem. One of the big issues right now is that the Hummingbird API is in a bad state and difficult to work with. I suggest using MyAnimeList (or offline) for now.

**Comment by wopian** [comment]
The Hummingbird API has never had a problem dealing with lists. The only feasible way this is happening is bad implementation on the client side.

**Comment by tofuness** [comment]
@wopian
My concerns:
- There is no manga API even though there is manga on the website.
- API hangs for people with large lists.
- `/anime/myanimelist:{malid}` from V2 doesn't seem to be completely accurate.

@matthewdias
What is your HB username?

**Comment by matthewdias** [comment]
matthewdias. I don't have anywhere close to a long list.

**Comment by wopian** [comment]
> API hangs if people have large lists.

A simple workaround it to send a request for each status type.

HB sync shouldn't even be using the MAL ID for anime though?

**Comment by tofuness** [comment]
> HB sync shouldn't even be using the MAL ID for anime though?

I agree. Mistake from my side to rely on the V2 endpoint. When I built the `syncer` for HB I was thinking about allowing people to freely sync between services which turned out to be more difficult than I thought.

**Comment by matthewdias** [comment]
I'm pretty sure the way HAPU handles it is just by scrobbling to both. theres not much of a use case for syncing them directly.
