### ISSUE TITLE
Feature Request: Sync to Account

### ISSUE THREAD

**Issue by JasonEtco** [tofuness/Toshocat#7]
Seems like an obvious one so I'm sure you guys have thought of it, but it would be great if my anime list would sync between my two different computers.

Unless this is solved by just using MyAnimeList or Hummingbird as the main service? If so, should be a little more clear through some kind of user onboarding.

**Comment by tofuness** [comment]
The "Toshocat service" currently uses local storage (Electron) and I have currently no plans on building a server that handles syncing between multiple computers.

> Unless this is solved by just using MyAnimeList or Hummingbird as the main service? 

Yes! I recommend registering a MyAnimeList account. Your list will be stored on their website and can be synced between multiple computers. 

> If so, should be a little more clear through some kind of user onboarding.

I totally agree. Definitely need to provide a better onboarding experience.

**Comment by JasonEtco** [comment]
Sounds good! Great job by the way, it works really well.
